### ISSUE TITLE
Adding Redis support to freediameter(instead of mySQL)

### ISSUE THREAD

**Issue by psup17** [Metaswitch/freeDiameter#15]
Hi, I would just like some information, if possible, on building a Redis db extension for freediameter. I can't find any documentation except for the sample extensions and I'm just not sure where to start. I would be using the hiredis c library to link to a redis database, just need to figure out how to incorporate that into a freediameter extension to use instead of mySQL. Thanks so much for any help at all!

**Comment by mirw** [comment]
Hi,

Just a heads-up that this isn't the master freeDiameter repository - I think that's hosted on mercurial over at http://www.freediameter.net/hg/freeDiameter.  This is a git clone of it that we use as part of [Project Clearwater](http://www.projectclearwater.org/).  You might have more luck over on the official freeDiameter mailing list at http://www.freediameter.net/trac/wiki/Developers.

Having said that, the freeDiameter extensions mechanism is very easy to work with.  I think the key question would be what Diameter "application" you are trying to implement - is it for authorization or accounting, and do you have a defined set of commands and AVPs you need to encode.  As an example for a mySQL-backed implementation of the Diameter SIP application ([RFC 4740](https://tools.ietf.org/html/rfc4740)), see the `app_sip` extension below `extensions/app_sip`.

I hope that helps, but as I say, you're probably better off asking on the official mailing list.

Matt

**Comment by psup17** [comment]
My bad, thanks for your time and help!
